"""
===============================================================================
presentation_cache.py
===============================================================================
Runtime figure-cache paths.

Responsibilities:
  - Build portable runtime cache paths.
  - Resolve generated runtime figures without consulting repository assets.
  - Save Matplotlib figures without pickling executable Python objects.

Design principles:
  - Runtime cache entries are disposable and never treated as curated
    scientific evidence.

Boundaries:
  - Only explicit save calls create directories.

Notes:
  - Missing entries are regenerated by the notebook from its prepared
    dataset.
===============================================================================
"""

from __future__ import annotations

import re
from pathlib import Path

from matplotlib.figure import Figure

from ..config.config_paths import ProjectPaths, default_paths

__all__ = ["figure_path", "resolve_cached_figure_path", "sanitize_name", "save_figure"]

_UNSAFE_NAME = re.compile(r"[^a-z0-9_.-]+")


def sanitize_name(value: str) -> str:
    """Normalize text into a stable lowercase filename component.

    Parameters
    ----------
    value
        Dataset or figure name to sanitize.

    Returns
    -------
    str
        Portable lowercase filename component.

    Raises
    ------
    ValueError
        If no usable alphanumeric filename content remains.
    """
    normalized = value.lower().replace("\u2013", "-").replace("\u2014", "-")
    result = _UNSAFE_NAME.sub("_", normalized).strip("._")
    if not result:
        raise ValueError("Name does not contain a usable filename component.")
    return result


def figure_path(
    dataset_name: str,
    figure_name: str,
    *,
    paths: ProjectPaths | None = None,
    create_parent: bool = False,
) -> Path:
    """Build the generated runtime PNG cache path.

    Parameters
    ----------
    dataset_name
        Dataset namespace for the figure cache.
    figure_name
        Stable figure identifier.
    paths
        Optional project path contract.
    create_parent
        Whether missing runtime parent directories are created.

    Returns
    -------
    pathlib.Path
        Sanitized runtime PNG path.

    Raises
    ------
    ValueError
        If a dataset or figure name cannot be sanitized.
    """
    project_paths = paths or default_paths()
    destination = project_paths.cache / sanitize_name(dataset_name) / "figures" / f"{sanitize_name(figure_name)}.png"
    if create_parent:
        destination.parent.mkdir(parents=True, exist_ok=True)
    return destination


def resolve_cached_figure_path(
    dataset_name: str,
    figure_name: str,
    *,
    paths: ProjectPaths | None = None,
) -> Path | None:
    """Resolve an existing generated runtime figure.

    Parameters
    ----------
    dataset_name
        Dataset namespace for runtime figures.
    figure_name
        Stable figure identifier.
    paths
        Optional project path contract.

    Returns
    -------
    pathlib.Path | None
        Existing runtime figure path, otherwise ``None``.

    Raises
    ------
    ValueError
        If a dataset or figure name cannot be sanitized.
    """
    runtime = figure_path(dataset_name, figure_name, paths=paths)
    return runtime if runtime.is_file() else None


def save_figure(
    figure: Figure,
    dataset_name: str,
    figure_name: str,
    *,
    paths: ProjectPaths | None = None,
) -> Path:
    """Save a Matplotlib figure into the generated runtime cache.

    Parameters
    ----------
    figure
        Figure to write as PNG.
    dataset_name
        Dataset cache namespace.
    figure_name
        Stable figure identifier.
    paths
        Optional project path contract.

    Returns
    -------
    pathlib.Path
        Written runtime PNG path.

    Raises
    ------
    ValueError
        If a dataset or figure name cannot be sanitized.
    OSError
        If the destination cannot be created or written.
    """
    destination = figure_path(
        dataset_name,
        figure_name,
        paths=paths,
        create_parent=True,
    )
    figure.savefig(destination, bbox_inches="tight")
    return destination
